### ISSUE TITLE
Invalid calling object in IE

### ISSUE THREAD

**Issue by Robertbaelde** [angular/angular.js#10807]
Hi, 

My web app runs perfectly in all browsers except IE (all versions).
When i run the app in IE11 i get the following errors:
TypeError: Invalid calling object
   at isArray (http://bitscan.net/webshopv2/vendor/js/angular-local-storage.js:4:3)
   at addToLocalStorage (http://bitscan.net/webshopv2/vendor/js/angular-local-storage.js:174:14)
   at set (http://bitscan.net/webshopv2/app/js/app.js:225:4)
   at Anonymous function (http://bitscan.net/webshopv2/app/js/app.js:106:7)
   at Anonymous function (http://bitscan.net/webshopv2/vendor/js/angular.js:7946:11)
   at wrappedCallback (http://bitscan.net/webshopv2/vendor/js/angular.js:11319:15)
   at wrappedCallback (http://bitscan.net/webshopv2/vendor/js/angular.js:11319:15)
   at Anonymous function (http://bitscan.net/webshopv2/vendor/js/angular.js:11405:11)
   at Scope.prototype.$eval (http://bitscan.net/webshopv2/vendor/js/angular.js:12412:9)
   at Scope.prototype.$digest (http://bitscan.net/webshopv2/vendor/js/angular.js:12224:15)

I couldn't find a bug or an item about this errors in the docs?
You can check the code here: http://bitscan.net/shop/v2/qnyqZIJfGv

**Comment by pkozlowski-opensource** [comment]
@Robertbaelde we will need to ask you to isolate the error so we can help with this one. Could you please narrow down your problem to the essential bits and provide a minimal reproduce scenario using http://plnkr.co/ or similar?

Otherwise it will be very hard to act on this one, I'm afraid.

**Comment by pkozlowski-opensource** [comment]
BTW, the stack trace points to the error originating outside of AngularJS - the throwing party is https://github.com/grevory/angular-local-storage

**Comment by caitp** [comment]
@Robertbaelde the issue is that angular-local-storage is using the Window object's `toString` method, which apparently does not like to be called on non-Window objects (or maybe just not "all" values) in IE11, and does not fall back on `O.p.toString` in case of failure.

**Comment by caitp** [comment]
(this is in no way angular related, but it might be worth filing a bug on IE to try to improve interop with other browsers a bit? or even a better error message would probably help people a lot there :x)

**Comment by caitp** [comment]
yeah, bit more investigation shows it just doesn't like to be called on non-windows at all in IE11. Fun! Easy fix for angular-local-storage though
