### ISSUE TITLE
Error thrown when a simple transclusion is mixed up with interpolation

### ISSUE THREAD

**Issue by MoonStorm** [angular/angular.js#11304]
```
TypeError: undefined is not a function
    at forEach.attr (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:2943:15)
    at Object.JQLite.(anonymous function) [as attr] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:3042:9)
    at Object.$get.Attributes.$set (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:6907:28)
    at interpolateFnWatchAction (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:8187:28)
    at interpolateFnWatcher (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:10370:26)
    at Object.watchGroupAction [as fn] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:14749:13)
    at Scope.$get.Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:15077:29)
    at Scope.$get.Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:15341:24)
    at bootstrapApply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:1517:15)
    at Object.invoke (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.js:4260:17)
```

It took me a while to narrow down the conditions for the error I was seeing in the console.

```
        .directive("testDirective", [function () {
            return {
                restrict:"A",
                transclude:"element",
                link:function(scope, instanceElement, tAttrs, ctrl, transclusionFn){
                    transclusionFn(function(clone, scope){
                        instanceElement.after(clone);
                    });
                }
            };
        }]); 
```
```
<div test-directive="" dir-var="{{testVar}}"></div>
```

[Here is the Fiddle](https://jsfiddle.net/MoonStorm/qbge5qse/)

The bug seems to be caused by some logic which apparently attempts to set attributes on the comment element, produced as a result of the `` transclude:"element" ``.

**Comment by MoonStorm** [comment]
Looking at the source code for the ngIf directive, which acts in a similar way, I realized that one is using a high priority. 

I was very surprised seeing that lifting the priority for my directive above 100 makes the error disappear. What's going on?!?

**Comment by Narretz** [comment]
Since. 1.4.0-beta.6 jqlite now aborts when trying to set attr on comments, attributes and text nodes: https://github.com/angular/angular.js/commit/bb5bf7f8162d11610a53428e630b47030bdc38e5 
I tested you fiddle with this version and there's no error anymore. Apart from the error thrown, was there another bug or did it work correctly?

**Comment by MoonStorm** [comment]
No, that appeared to have been the only thing. Everything else works well.

**Comment by Narretz** [comment]
Great, I will close this then!
