### ISSUE TITLE
Android Webview, using goBack(), route states and pages containing iframe with ng-src

### ISSUE THREAD

**Issue by PuKoren** [angular/angular.js#11346]
## Overview of the Issue
On my Android Webview, I do use the goback method goBack() on a page with angular, and an iframe with a ng-src attribute.

I have to following message: 
```
Error: [$location:ipthprfx] Invalid url "about:blank", missing path prefix
```

Everything works ok on desktop browsers. It looks like the iframe is first loaded setting a src to about:blank and then the ng-src loads the true url

## Motivation for or Use Case
I expect that when I use goBack(), the browser actually goes back.

## Angular Version(s)
1.3.15

## Browsers and Operating System
Native Android browser (4.3)

## Reproduce the Error
Open a webview on a page with a link to another page with an iframe with no src and an ng-src, then once page is loaded press back and see the error in the console

## Stack trace:

```
E/Web Console( 1936): Error: [$location:ipthprfx] Invalid url "about:blank", missing path prefix "http://xxx.xxx.xxx/".
E/Web Console( 1936): http://errors.angularjs.org/1.3.6/$location/ipthprfx?p0=about%3Ablank&p1=http%3A%2F%2Fxxx.xxx.xxx%2F
E/Web Console( 1936):     at http://xxx.xxx.xxx/components/angular/angular.js:63:12
E/Web Console( 1936):     at Object.LocationHtml5Url.$$parse (http://xxx.xxx.xxx/components/angular/angular.js:10556:13)
E/Web Console( 1936):     at http://xxx.xxx.xxx/components/angular/angular.js:11342:19
E/Web Console( 1936):     at Scope.$eval (http://xxx.xxx.xxx/components/angular/angular.js:14353:28)
E/Web Console( 1936):     at Scope.$digest (http://xxx.xxx.xxx/components/angular/angular.js:14169:31)
E/Web Console( 1936):     at http://xxx.xxx.xxx/components/angular/angular.js:11361:43
E/Web Console( 1936):     at http://xxx.xxx.xxx/components/angular/angular.js:5098:7
E/Web Console( 1936):     at forEach (http://xxx.xxx.xxx/components/angular/angular.js:322:20)
E/Web Console( 1936):     at fireUrlChange (http://xxx.xxx.xxx/components/angular/angular.js:5097:5)
E/Web Console( 1936):     at cacheStateAndFireUrlChange (http://xxx.xxx.xxx/components/angular/angular.js:5073:5) at http://xxx.xxx.xxx/components/angular/angular.js:11562

```

**Comment by PuKoren** [comment]
Error was due to the use of LoadDataWithContent without a valid history url, and is on Android side.
