### ISSUE TITLE
angular-messageFormat select statement bug

### ISSUE THREAD

**Issue by brycecr** [angular/angular.js#11414]
I have the following in my template
```
<span>
   <!--i18n: Gender fun-->
   {{model.gender, select,
         male   {He gave me a cactus}
         female {She gave me a cactus}
         other  {They gave me a cactus}
   }}
   <!--/i18n-->
</span>
```
And I am getting an error that says 'other is a required option' with stacktrace:

```
at http://localhost:1080/static/lib/angular/angular.min.js:6:434
    at new MessageSelectorBase (http://localhost:1080/static/lib/angular/angular-messageFormat.js:102:11)
    at MessageSelectorBase.SelectMessage (http://localhost:1080/static/lib/angular/angular-messageFormat.js:165:23)
    at MessageFormatParser.ruleSelectKeyword (http://localhost:1080/static/lib/angular/angular-messageFormat.js:577:21)
    at MessageFormatParser.run (http://localhost:1080/static/lib/angular/angular-messageFormat.js:451:12)
    at interpolate (http://localhost:1080/static/lib/angular/angular-messageFormat.js:891:14)
```

I tried copy-pasting the example from the docs for the messageformat pr and got the same result.

**Comment by brycecr** [comment]
@chirayuk

**Comment by brycecr** [comment]
I should mention also that the declarative plurals are always going to `other`. It looks like the MessageFormatParser objects are somehow borked and `this.choices` returns `{}`. I am on ea9fd82.

**Comment by chirayuk** [comment]
Yup.  This is a bug.  I'll be fixing it in the next day or two.
