### ISSUE TITLE
TypeError: Object.keys: argument is not an Object for $http(post) in ie11

### ISSUE THREAD

**Issue by p09** [angular/angular.js#11487]
$http({
		method: 'POST',
		url: '/api/create',
		data: JSON.stringify({name:'testName',id:'testId1',description:'testing....'}),
		headers: {
		    "Content-Type": "application/json;charset=UTF-8"
			}
		}).then(function(){alert("success..");},function(){alert("failure...");});

the same $http call works in firefox and chrome but fails in ie11 with the error:

TypeError: Object.keys: argument is not an Object
   at w (http://***************/angular1.3.15.min.js:8:241)
   at Anonymous function (http://***************/angular1.3.15.min.js:79:315)
   at k (http://***************/angular1.3.15.min.js:79:255)
   at /***************/
   at Anonymous function (http://***************/angular1.3.15.min.js:199:291)
   at f (http://***************/angular1.3.15.min.js:216:74)
   at n.prototype.$eval (http://***************/angular1.3.15.min.js:126:4)
   at n.prototype.$apply (http://***************/angular1.3.15.min.js:126:217)
   at Anonymous function (http://***************/angular1.3.15.min.js:216:124)
   at c (http://***************/angular1.3.15.min.js:32:384)

Another intersting thing is that the same code woks in ie11 if i use an older version of Angular say 1.2.8.

Please reply asap

**Comment by lamemmv** [comment]
I had the same issue
