### ISSUE TITLE
$http.get not working...

### ISSUE THREAD

**Issue by pawangupta78** [angular/angular.js#11559]
I am trying to make a simple call, where I am trying to load json data from a file using $http.get and getting exception
SyntaxError: Unexpected token a
    at Object.parse (native)
    at qc (http://localhost:8080/Angular/js/angular.min.js:14:245)
    at Zb (http://localhost:8080/Angular/js/angular.min.js:76:423)
    at http://localhost:8080/Angular/js/angular.min.js:77:283
    at r (http://localhost:8080/Angular/js/angular.min.js:7:302)
    at Zc (http://localhost:8080/Angular/js/angular.min.js:77:265)
    at c (http://localhost:8080/Angular/js/angular.min.js:78:414)
    at http://localhost:8080/Angular/js/angular.min.js:112:113
    at n.$get.n.$eval (http://localhost:8080/Angular/js/angular.min.js:126:15)
    at n.$get.n.$digest (http://localhost:8080/Angular/js/angular.min.js:123:106)

and this is my code...

myApp.run(function ($http) {
        $http.get("http://localhost:8080/Angular/app/todo.json").success(function (data) {
            //model.items = data;
            console.log(data.records);
        }).error(function(data){
            console.log("There is an issue")
        });
    });

Here, I have tried all permutation and combinations to load json file but somehow it is not working.
I am using tomcat 7 as webserver.

Any help would be appreciated.
thanks.

**Comment by pkozlowski-opensource** [comment]
You are not showing us the essential bit... which is your JSON file. I would bet that it is not a valid JSON, hence the error.

At any rate this is a general support question (unless a bug is proven with a live reproduce scenario, that is!) and as such should be asked using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by pawangupta78** [comment]
oops my bad... I put it at wrong place. i will take care of things next time.
