### ISSUE TITLE
TypeError: Cannot read property '' of undefined (when using 1.4.x)

### ISSUE THREAD

**Issue by wil93** [angular/angular.js#11877]
I'm trying to make the sample angular-material app work on Angular 1.4.x (https://github.com/angular/material-start), but I get this error:

```
TypeError: Cannot read property '' of undefined
at lookup (angular-animate.js:617)
at animationRunner (angular-animate.js:681)
at performAnimation (angular-animate.js:1284)
at angular-animate.js:959
at angular-animate.js:539
at Scope.$get.Scope.$digest (angular.js:15589)
at Scope.$get.Scope.$apply (angular.js:15807)
at bootstrapApply (angular.js:1628)
at Object.invoke (angular.js:4426)
at doBootstrap (angular.js:1626)
```

I only did update `angular`, `angular-aria` and `angular-animate` to 1.4.0-rc2 (via bower).

This is the output of `bower list`:

```
angular-material-starter#0.0.1 /media/myusbdrive/material-start
├── angular#1.4.0-rc.2
├─┬ angular-animate#1.3.15 (1.3.16-build.111+sha.0515614 available, latest is 1.4.0-rc.2)
│ └── angular#1.4.0-rc.2 incompatible with 1.3.15 (1.3.15 available, latest is 1.4.0-rc.2)
├─┬ angular-aria#1.4.0-rc.2
│ └── angular#1.4.0-rc.2
└─┬ angular-material#0.8.3 (latest is 0.9.0)
  ├── angular#1.4.0-rc.2 incompatible with 1.3.x (1.3.16-build.111+sha.0515614 available, latest is 1.4.0-rc.2)
  ├─┬ angular-animate#1.3.15 (1.3.16-build.111+sha.0515614 available, latest is 1.4.0-rc.2)
  │ └── angular#1.4.0-rc.2
  └─┬ angular-aria#1.4.0-rc.2 incompatible with 1.3.x (1.3.16-build.111+sha.0515614 available, latest is 1.4.0-rc.2)
    └── angular#1.4.0-rc.2
```

**Comment by gkalpak** [comment]
Seems like you are using an older version of angular-animate.
You should use the version that matches angular (i.e. 1.4.0-rc.2).

**Comment by wil93** [comment]
Yes I somehow had an old version of angular-animate, now I updated it, but I get the same TypeError...

This is the current output of `bower list`:

```
angular-material-starter#0.0.1 /run/media/wil93/usb/material-start
├── angular#1.4.0-rc.2
├─┬ angular-animate#1.4.0-rc.2
│ └── angular#1.4.0-rc.2
├─┬ angular-aria#1.4.0-rc.2
│ └── angular#1.4.0-rc.2
└─┬ angular-material#0.9.3
  ├── angular#1.4.0-rc.2
  ├─┬ angular-animate#1.4.0-rc.2
  │ └── angular#1.4.0-rc.2
  └─┬ angular-aria#1.4.0-rc.2
    └── angular#1.4.0-rc.2
```

**Comment by wil93** [comment]
No, my bad, it was the cache... The TypeError is gone.

Now I get these 2 errors (maybe I should open a different issue or rename this one?):

```
Uncaught ReferenceError: goog is not defined(anonymous function) @ angular-material.js:7
```

and:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module starterApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:nomod] Module 'ngMaterial' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.0-rc.2/$injector/nomod?p0=ngMaterial
    at REGEX_STRING_REGEXP (http://localhost:8000/bower_components/angular/angular.js:68:12)
    at http://localhost:8000/bower_components/angular/angular.js:1953:17
    at ensure (http://localhost:8000/bower_components/angular/angular.js:1877:38)
    at module (http://localhost:8000/bower_components/angular/angular.js:1951:14)
    at http://localhost:8000/bower_components/angular/angular.js:4338:22
    at forEach (http://localhost:8000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:8000/bower_components/angular/angular.js:4322:5)
    at http://localhost:8000/bower_components/angular/angular.js:4339:40
    at forEach (http://localhost:8000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:8000/bower_components/angular/angular.js:4322:5)
http://errors.angularjs.org/1.4.0-rc.2/$injector/modulerr?p0=ngMaterial&p1=…2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A4322%3A5)
    at REGEX_STRING_REGEXP (http://localhost:8000/bower_components/angular/angular.js:68:12)
    at http://localhost:8000/bower_components/angular/angular.js:4361:15
    at forEach (http://localhost:8000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:8000/bower_components/angular/angular.js:4322:5)
    at http://localhost:8000/bower_components/angular/angular.js:4339:40
    at forEach (http://localhost:8000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:8000/bower_components/angular/angular.js:4322:5)
    at createInjector (http://localhost:8000/bower_components/angular/angular.js:4248:11)
    at doBootstrap (http://localhost:8000/bower_components/angular/angular.js:1625:20)
    at bootstrap (http://localhost:8000/bower_components/angular/angular.js:1646:12)
http://errors.angularjs.org/1.4.0-rc.2/$injector/modulerr?p0=starterApp&p1=…F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1646%3A12)REGEX_STRING_REGEXP @ angular.js:68(anonymous function) @ angular.js:4361forEach @ angular.js:336loadModules @ angular.js:4322createInjector @ angular.js:4248doBootstrap @ angular.js:1625bootstrap @ angular.js:1646angularInit @ angular.js:1540(anonymous function) @ angular.js:28040trigger @ angular.js:2973eventHandler @ angular.js:3247
```

**Comment by lili21** [comment]
Just follow the error message, try to digg in angular-material.js.

**Comment by gkalpak** [comment]
This is an issue/bug with `ngMaterial#0.9.3`. You track the relevant issue https://github.com/angular/material/issues/2858

It should work if you (somehow) use a previous version or the later master snapshot (e.g. https://github.com/angular/bower-material/tree/v0.9.3-master-7d3c02a).

Closing as there doesn't seem to be related to Angular core.
(Feel free to open a new issue if you stumble upon a different bug.)
