### ISSUE TITLE
angular decorators are broken.

### ISSUE THREAD

**Issue by sochka** [angular/angular.js#12177]
Hi, when I add this simple code
```
widgetApi.decorator('translateDirective', function ($delegate) {
});
```
I get this error (which seems to be an internal angular error).

```
TypeError: Cannot read property 'length' of undefined
    at addDirective (http://localhost:8080/components/angular/angular.js:8172:35)
    at collectDirectives (http://localhost:8080/components/angular/angular.js:7562:11)
    at compileNodes (http://localhost:8080/components/angular/angular.js:7427:22)
    at compile (http://localhost:8080/components/angular/angular.js:7338:15)
    at applyDirectivesToNode (http://localhost:8080/components/angular/angular.js:7822:33)
    at compileNodes (http://localhost:8080/components/angular/angular.js:7431:15)
    at compileNodes (http://localhost:8080/components/angular/angular.js:7443:15)
    at compileNodes (http://localhost:8080/components/angular/angular.js:7443:15)
    at compile (http://localhost:8080/components/angular/angular.js:7338:15)
    at ngIncludeFillContentDirective.link (http://localhost:8080/components/angular/angular.js:23926:9) <ng-include src="skin.url" class="ng-scope">(anonymous function) @ angular.js:12221$get @ angular.js:9055invokeLinkFn @ angular.js:8606nodeLinkFn @ angular.js:8113compositeLinkFn @ angular.js:7514publicLinkFn @ angular.js:7388$get.boundTranscludeFn @ angular.js:7533controllersBoundTransclude @ angular.js:8140(anonymous function) @ angular.js:23874processQueue @ angular.js:14454(anonymous function) @ angular.js:14470$get.Scope.$eval @ angular.js:15719$get.Scope.$digest @ angular.js:15530$get.Scope.$apply @ angular.js:15824bootstrapApply @ angular.js:1628invoke @ angular.js:4426doBootstrap @ angular.js:1626bootstrap @ angular.js:1646angular.bootstrap @ ocLazyLoad.js:924(anonymous function) @ app.js:565(anonymous function) @ app.js:565__exec @ system.src.js:1164load.metadata.execute @ system.src.js:2425linkDynamicModule @ system.src.js:1860link @ system.src.js:1722Promise.all.then.execute @ system.src.js:2052doDynamicExecute @ system.src.js:681link @ system.src.js:876doLink @ system.src.js:548updateLinkSetOnLoad @ system.src.js:596(anonymous function) @ system.src.js:417
```

Angular 1.4.1 and 1.4.0, Linux Mint 17.2, latest Google Chrome beta.

**Comment by Narretz** [comment]
It's necessary to return the $delegate from the decorator. Have you tried that?

**Comment by lgalfaso** [comment]
and a plunker showing the error would be ideal

**Comment by sochka** [comment]
Well, I tried 

```

widgetApi.decorator('translateDirective', function ($delegate) {
  window.alert('This works');
  return $delegate;
});
```

And even `alert` function wasn't called, therefore error happens even before returning `$delegate`. I'm not sure about setting up a plunker, because I guess this works under normal circumstances and my code is not easily plunker-able with lots of dependencies, using of `system.js` and ES6 code with compilation phase.

I can only show you the whole repo - here is it https://github.com/kpi-wdc/wdc/tree/develop/ and I tried to put shown code in the very end of this file https://github.com/kpi-wdc/wdc/blob/develop/assets/js/widget-api.js

**Comment by lgalfaso** [comment]
I do not know if someone wants to take a look at this, but without a plunker there is not a lot that can be done.

BTW, I still think that the reason is the one outlined https://github.com/angular/angular.js/issues/12177#issuecomment-113913068

**Comment by ryanhart2** [comment]
This plunker shows a working example of a decorated directive: http://plnkr.co/edit/UWR8DgCxycCCZXB6QFhV?p=preview

If the last line is commented out, this results in "TypeError: Cannot read property 'length' of undefined"
```js
.decorator('standardDirective', function($delegate) {
  console.log('I got here');
  var directive = $delegate[0];
  directive.template = "<p>{{version}} + enhancements</p>";
  //return $delegate;
});
```

**Comment by Narretz** [comment]
There's not much we can do without a clear reproduction. Please try to provide one - we cannot realistically check complete projects for what might be usage errors.
