### ISSUE TITLE
Angular animate - error in nextTick/runNextTask

### ISSUE THREAD

**Issue by mdudek** [angular/angular.js#12496]
Occured in v1.4.3:

```
Stack:TypeError: undefined is not a function
    at runNextTask (file:///android_asset/www/js/lib/angular-animate.js:313:5)
    at nextTick (file:///android_asset/www/js/lib/angular-animate.js:297:7)
    at scheduler (file:///android_asset/www/js/lib/angular-animate.js:268:5)
    at file:///android_asset/www/js/lib/angular-animate.js:2744:15
    at forEach (file:///android_asset/www/js/lib/angular.js:336:20)
    at file:///android_asset/www/js/lib/angular-animate.js:2725:9
    at Scope.$digest (file:///android_asset/www/js/lib/angular.js:15733:36)
    at Scope.$apply (file:///android_asset/www/js/lib/angular.js:15951:24
```

**Comment by Narretz** [comment]
Can you please provide a demo that reproduces this error?

**Comment by mdudek** [comment]
It happened once in our cordova app, it was in code like this:

```
element.bind('click', function(){
      $scope.$apply(function () {
          console.log('click');
          ...
      });
});
```

**Comment by Narretz** [comment]
This is unfortunately not enough to make this actionable. I'll close this issue. Please reopen if you can provide more info.
