### ISSUE TITLE
Unable to install AngularJs on Windows 7

### ISSUE THREAD

**Issue by gmnayak** [angular/angular.js#12629]
Hi, 
I'm trying to setup development environment for AngularJS. After repeated attempts it fails with the below message:

```
C:\angular.js>npm install
npm ERR! git rev-list -n1 ced17cbe52c1412b2ada53160432a5b681f37cd7: fatal: bad o
bject ced17cbe52c1412b2ada53160432a5b681f37cd7
npm ERR! git rev-list -n1 ced17cbe52c1412b2ada53160432a5b681f37cd7:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 ced17cbe52c1412
b2ada53160432a5b681f37cd7
npm ERR! fatal: bad object ced17cbe52c1412b2ada53160432a5b681f37cd7
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular.js\npm-debug.log

npm debug.log file contains the below(Last few lines)
3357 verbose etag https://registry.npmjs.org/dgeni-packages from cache
3358 verbose get saving dgeni-packages to C:\Users\002812\AppData\Roaming\npm-cache\registry.npmjs.org\dgeni-packages\.cache.json
3359 silly cache afterAdd dgeni-packages@0.10.17
3360 verbose afterAdd C:\Users\002812\AppData\Roaming\npm-cache\dgeni-packages\0.10.17\package\package.json not in flight; writing
3361 verbose afterAdd C:\Users\002812\AppData\Roaming\npm-cache\dgeni-packages\0.10.17\package\package.json written
3362 verbose stack Error: Command failed: git -c core.longpaths=true rev-list -n1 ced17cbe52c1412b2ada53160432a5b681f37cd7
3362 verbose stack fatal: bad object ced17cbe52c1412b2ada53160432a5b681f37cd7
3362 verbose stack
3362 verbose stack     at ChildProcess.exithandler (child_process.js:751:12)
3362 verbose stack     at ChildProcess.emit (events.js:110:17)
3362 verbose stack     at maybeClose (child_process.js:1015:16)
3362 verbose stack     at Socket.<anonymous> (child_process.js:1183:11)
3362 verbose stack     at Socket.emit (events.js:107:17)
3362 verbose stack     at Pipe.close (net.js:485:12)
3363 verbose cwd C:\angular.js
3364 error Windows_NT 6.1.7601
3365 error argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3366 error node v0.12.7
3367 error npm  v2.11.3
3368 error code 128
3369 error Command failed: git -c core.longpaths=true rev-list -n1 ced17cbe52c1412b2ada53160432a5b681f37cd7
3369 error fatal: bad object ced17cbe52c1412b2ada53160432a5b681f37cd7
3370 error If you need help, you may report this error at:
3370 error     <https://github.com/npm/npm/issues>
3371 verbose exit [ 1, true ]
```

**Comment by Narretz** [comment]
I don't see any angular related error there. Maybe something is wrong with your environment? A git command seems to have failed.

**Comment by gmnayak** [comment]
Resolved!

Issue was with devDependencies "grunt-jasmine-node" mentioned in angularjs package.json file.

Changed it from "grunt-jasmine-node": "git://github.com/vojtajina/grunt-jasmine-node.git#fix-grunt-exit-code" to "grunt-jasmine-node": "~2.0.1"

grunt-jasmine-node was the referring to the fatal object

**Comment by Narretz** [comment]
Good to hear! I just tested it too, no problems here.
