### ISSUE TITLE
ng-include doesn't work with src URL

### ISSUE THREAD

**Issue by vinkaga** [angular/angular.js#12676]
For the following code (also found on code pen http://codepen.io/vinkaga/pen/gpVKyR?editors=100)
```JavaScript
<html lang="en" ng-app>
<head>
  <meta charset="UTF-8">
  <title>Example - ng-include</title>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js"></script>
</head>
  
<body>
  <div ng-include src="'http://codepen.io/vinkaga/pen/aOgayK.html'"></div>
</body>
</html>
```
The output displayed is blank page. I can make ng-include work if I define the html to be included in the script tag but I can't make it work with a URL.

**Comment by NickBolles** [comment]
If you click on your codepen link and click `F12` you can see in the console that angular is throwing the following error

```
Error: [$sce:insecurl] http://errors.angularjs.org/1.4.4/$sce/insecurl?p0=http%3A%2F%2Fcodepen.io%2Fvinkaga%2Fpen%2FaOgayK.html
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:6:416
    at $get.getTrusted (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:140:93)
    at Object.$get.d.(anonymous function) [as getTrustedResourceUrl] (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:141:350)
    at e (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:143:297)
    at Object.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:255:76)
    at Object.fn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:115:256)
    at n.$get.n.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:130:310)
    at n.$get.n.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:133:330)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js:19:479
```
Which leads you to [this page](https://docs.angularjs.org/error/$sce/insecurl?p0=http:%2F%2Fcodepen.io%2Fvinkaga%2Fpen%2FaOgayK.html)

and should be able to help you out more. You need to configure your [whitelist](https://docs.angularjs.org/api/ng/provider/$sceDelegateProvider#resourceUrlWhitelist)

**Comment by vinkaga** [comment]
@NickBolles, thanks, updating it slightly makes it work.
http://codepen.io/vinkaga/pen/gpVKyR?editors=100

**Comment by NickBolles** [comment]
Np. And that's the best solution that you have there.
