### ISSUE TITLE
unable to do bower install after cloning angular

### ISSUE THREAD

**Issue by shaunstanislaus** [angular/angular.js#12931]
```bash
shaunstanislaus@Master ~/workspace/MEAN/fullstack_practice/app/angular.js (master) $ bower installmodule.js:338
    throw err;
    ^

Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:9:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

```

**Comment by shaunstanislaus** [comment]
my bower was outdated i uninstall.

heres how you fixed it if anyone of you encounter it.

```bash
npm uninstall -g bower
npm install -g bower

```
