### ISSUE TITLE
Protractor e2e tests: Timing issues while accessing browser log

### ISSUE THREAD

**Issue by vinkaga** [angular/angular.js#13116]
In my e2e tests, I have assertions to check for unexpected errors in browser log. Some tests cause expected errors which also have checks for browser errors.

Unfortunately, I am running into timing issues with number of errors present in the browser log. In the attached code, the browser gets 2 errors, one for favicon.ico and another one for 404.jpg which is accessed as a resource.

I can see these 2 errors in the browser log if I put a ```browser.pause()``` in the test. But when I assert for presence of these 2 error logs, it doesn't always show both errors even after waiting for 5000ms. The console output is 
```sh
$  protractor protractor-conf.js
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.10.110:56388/wd/hub
Started
[ Object {
    level: Object { value: 1000, name: 'SEVERE' },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (File not found)',
    timestamp: 1445113763657,
    type: '' } ]
F

Failures:
1) E2E Test
  Message:
    Expected 1 to equal 2.
  Stack:
    Error: Failed expectation
        at /Users/vagarwal/dev/e2e/spec.js:13:31
        at Array.forEach (native)
        at process._tickCallback (node.js:366:9)

1 spec, 1 failure
Finished in 6.095 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

Here are the files. 
index.html
```HTML
<!DOCTYPE html>
<html ng-app="MyApp">

<head>
    <meta charset="utf-8" />
    <title>AngularJS MyApp</title>
    <script>
        document.write('<base href="' + document.location + '" />');
    </script>
</head>

<body>
<script src="https://code.angularjs.org/1.4.7/angular.js"></script>
<script src="https://code.angularjs.org/1.4.7/angular-resource.js"></script>

<script>
    var app = angular.module('MyApp', [
        'ngResource'
    ])
            .run(['$resource', function($resource) {
                $resource('/404.jpg').get();
            }]);

</script>
</body>

</html>
```
protractor-conf.js
```JavaScript
exports.config = {
	allScriptsTimeout: 11000,

	specs: [
		'spec.js'
	],

	capabilities: {
		'browserName': 'chrome'
	},

	chromeOnly: true,

	baseUrl: 'http://localhost:8000/',

	framework: 'jasmine2',

	jasmineNodeOpts: {
		defaultTimeoutInterval: 120000
	}
};
```
spec.js
```JavaScript
'use strict';

describe('E2E', function() {

	it('Test', function() {
		browser.get('/');
		browser.sleep(5000).then(function() {
			browser.manage().logs().get('browser').then(function(browserLog) {
				if (browserLog.length != 2) {
					console.log(browserLog);
				}
				// 2 errors, favicon.ico and 404.jpg
				expect(browserLog.length).toEqual(2);
			});
		});
	});

	// No error should be present
	afterEach(function() {
		browser.manage().logs().get('browser').then(function(browserLog) {
			if (browserLog.length != 0) {
				console.log(browserLog);
			}
			expect(browserLog.length).toEqual(0);
		});
	});
});
```

I have tried waiting for longer than 5000ms but that doesn't seem to get both errors either. What is a reliable way of fetching those errors from the browser log?

**Comment by petebacondarwin** [comment]
Should you not be chaining onto the promise from the `.get()`? I.E.

```
    it('Test', function() {
        browser.get('/').then(function() {
            browser.manage().logs().get('browser').then(function(browserLog) {
                if (browserLog.length != 2) {
                    console.log(browserLog);
                }
                // 2 errors, favicon.ico and 404.jpg
                expect(browserLog.length).toEqual(2);
            });
        });
    });
```

**Comment by petebacondarwin** [comment]
Also I think this is really a question for the Protractor issue tracker...
