### ISSUE TITLE
Getting  Error: [$compile:nonassign] while using Angular ui-bootstrap

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [angular/angular.js#13321]
Hi,I am getting the following error while navigating one page to another page using ui-bootstrap of Angular.js.

```
Error: [$compile:nonassign] http://errors.angularjs.org/1.4.6/$compile/nonassign?p0=%24state.current.name%20%3D%3D'principal.myplanManagement.myPlan'&p1=uibTab
    at Error (native)
    at http://oditek.in/Gofasto/js/angularjs.js:6:416
    at q (http://oditek.in/Gofasto/js/angularjs.js:74:45)
    at l (http://oditek.in/Gofasto/js/angularjs.js:74:120)
    at Object.<anonymous> (http://oditek.in/Gofasto/js/angularjs.js:116:15)
    at n.$digest (http://oditek.in/Gofasto/js/angularjs.js:130:71)
    at n.$apply (http://oditek.in/Gofasto/js/angularjs.js:133:236)
    at HTMLAnchorElement.<anonymous> (http://oditek.in/Gofasto/js/angularjs.js:253:36)
    at HTMLAnchorElement.m.event.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:4:8549)
    at HTMLAnchorElement.r.handle (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:4:5252)
```
I am explaining my code below.

```
<div>
 <uib-tabset>
 <uib-tab ui-sref="principal.myplanManagement.myTimeTable" active="$state.current.name =='principal.myplanManagement.myTimeTable'">
      <uib-tab-heading>Add MyTimeTable</uib-tab-heading>
    </uib-tab>
    <uib-tab ui-sref="principal.myplanManagement.myPlan" active="$state.current.name =='principal.myplanManagement.myPlan'">
      <uib-tab-heading>Add MyPlan</uib-tab-heading>
    </uib-tab>
    <uib-tab ui-sref="principal.myplanManagement.myWDS" active="$state.current.name=='principal.myplanManagement.myWDS'">
      <uib-tab-heading>Add MyWDS</uib-tab-heading>
    </uib-tab>
    </uib-tabset>
  <div ui-view></div>
</div>
```
When i am moving to Add MyPlan page this type of error i am getting in console.Please help me to resolve this error.

**Comment by pkozlowski-opensource** [comment]
@subhrajyotiw5rtc as [already asked](https://github.com/angular/angular.js/issues/13004) please don't open issues for general support questions but please direct them to an appropriate support channel instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Thnx!

**Comment by subhrajyotiw5rtc** [comment]
@pkozlowski-opensource  How can i get the appropriate support channel ? I have to fix this issue.Please help me.

**Comment by pkozlowski-opensource** [comment]
> How can i get the appropriate support channel 

From https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question:

> If you have questions about how to use AngularJS, please direct these to the Google Group discussion list or StackOverflow. We are also available on IRC and Gitter.
