### ISSUE TITLE
chromeHack method throws TypeError: optionElement[0].hasAttribute is not a function

### ISSUE THREAD

**Issue by rahulbpatel** [angular/angular.js#13874]
Hi,

I have a custom directive that replaces with template `<option ng-repeat>` and this ends up throwing an exception in chromeHack on line 28664:

```
TypeError: optionElement[0].hasAttribute is not a function
    at chromeHack (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:28664:24)
    at self.addOption (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:28745:5)
    at self.registerOption (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:28792:12)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:29133:22
    at invokeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:9039:9)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:8533:11)
    at compositeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:7929:13)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:8528:24)
    at compositeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:7929:13)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:8528:24) <!-- ngRepeat: item in data -->
```

**Reproducable**: always
**Angular Version(s)**: 1.4.8, 1.4.9
**Browsers and Operating System**:  Chrome Version 47.0.2526.111 m, Windows 10 64-bit
**Reproduce the Error**: http://plnkr.co/edit/UejSXqwfq320wtzN7HWG

**Comment by gkalpak** [comment]
This also happens on `v1.5.0-rc.1`. It's because we are calling `hasAttribute` on a comment.

**Comment by Narretz** [comment]
We've actually added a number of checks for comments, but it seems like this is another corner case. Given that this uses `replace` I'm not too keen on working on a fix. If someone wants to give it a shot, your're welcome. ;)
