### ISSUE TITLE
Error after update: Cannot read property '$id' of undefined

### ISSUE THREAD

**Issue by krasevych** [angular/angular.js#13981]
I updated to 1.5.0 and take this error:
```TypeError: Cannot read property '$id' of undefined
    at arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2001:19)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:16664:23)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2016:23)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:16928:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2079:22)
    at bootstrapApply (http://localhost:3000/bower_components/angular/angular.js:1694:15)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4604:19)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1692:14)
    at Object.angular.resumeBootstrap (http://localhost:3000/bower_components/angular/angular.js:1720:12)
    at maybeBootstrap (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:569:11)```

**Comment by Narretz** [comment]
Can you please provide a demo of the problem in a plnkr.co or similar?

**Comment by gkalpak** [comment]
It might be related to batarang (see https://github.com/angular/batarang/issues/285).

**Comment by krasevych** [comment]
it is a problem with AngularJS Batarang.
if I disabled Batarang it works ok.

**Comment by gkalpak** [comment]
That's is probably something that needs to be fixed in batarang.
But we need a demo (or at least a live example of something failing with batarang enabled).

**Comment by Narretz** [comment]
Let's focus the discussion in https://github.com/angular/batarang/issues/285
