### ISSUE TITLE
setting ng-pattern does and evaluation for mathematical expression

### ISSUE THREAD

**Issue by dreamerNcoder** [angular/angular.js#14423]
[AngularIssue.txt](https://github.com/angular/angular.js/files/216379/AngularIssue.txt)

Hi, 

I have and simple application where I have used ng-pattern like` '[A-Za-z].*',` and this regex is proper. I can create `new Regex('[A-Za-z].*') `

The page gives console error:
angular.js:13424Error: [$parse:syntax] http://errors.angularjs.org/1.5.3/$parse/syntax?p0=*&p1=is%20not%20a%20validNaNdentifier&p2=10&p3=%5BA-Za-z%5D.*&p4=*
    at Error (native)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:6:416
    at Object.s.throwError (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:223:470)
    at Object.s.identifier (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:222:203)
    at Object.s.primary (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:221:324)
    at Object.s.unary (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:220:6)
    at Object.s.multiplicative (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:219:265)
    at Object.s.additive (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:219:92)
    at Object.s.relational (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:218:442)
    at Object.s.equality (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js:218:267)

Attached a sample txt file. (Please rename .txt to .html ) and run it.

**Comment by gkalpak** [comment]
This is because `ngPattern` accepts an Angular expression and you passed the raw RegExp string.
Either pass an expression that evaluates to that string or use `pattern` which access the raw RegExp string.

E.g.:

```html
<input ... ng-pattern=".*" />   <!-- Invalid -->

<input ... pattern=".*" />   <!-- Valid -->

<input ... ng-pattern="'.*'" />   <!-- Valid -->

<!-- (In JS: `scope.myPattern = '.*';`) -->
<input ... ng-pattern="myPattern" />   <!-- Valid -->

```

--
That said, this is a general support question. In the future, please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
