### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by johnbendi** [angular/angular.js#14505]
When trying the build the project from master, `grunt package` gives the following feedback:
```
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: undefined is not a function
>>     at Array.filter (native)
>>     at getPreviousVersions (/opt/javascript/angular.js/lib/versions/version-info.js:111:8)
>>     at Object.<anonymous> (/opt/javascript/angular.js/lib/versions/version-info.js:204:47)
>>     at Module._compile (module.js:413:34)
>>     at Object.Module._extensions..js (module.js:422:10)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at Object.<anonymous> (/opt/javascript/angular.js/Gruntfile.js:5:19)

Running tasks: package
Warning: Task "package" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by gkalpak** [comment]
This is strange, because it works for me (and others :smiley:). Make sure you have cloned the repo correctly (e.g. all files are there).

What OS and Node/npm versions are you on ?

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
