### ISSUE TITLE
ngAnimate tests fail locally (locale?)

### ISSUE THREAD

**Issue by mprobst** [angular/angular.js#14535]
**What is the current behavior?**

On a vanilla master, lots of ngAnimate tests fail. At least some of those seem to be caused by locale issues because they compare `toString` of a float value without accounting for locale (note the `5.5` vs `5,5` failures below).

```
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active CSS staggering should apply a stagger based when an active ng-EVENT-stagger class with a transition-delay is detected FAILED
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:678:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] not to have class 'ng-enter'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:683:29)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:678:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] not to have class 'ng-enter'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:683:29)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:678:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] not to have class 'ng-enter'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:683:29)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:678:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] not to have class 'ng-enter'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:683:29)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active CSS staggering should apply a stagger based when for all provided addClass/removeClass CSS classes FAILED
  Expected [[object HTMLDivElement]] to have class 'red-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:742:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'green-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:743:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'blue-remove-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:744:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'red-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:742:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'green-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:743:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'blue-remove-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:744:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'red-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:742:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'green-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:743:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'blue-remove-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:744:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'red-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:742:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'green-add-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:743:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'blue-remove-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:744:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active CSS staggering should start on the highest stagger value if both transition and keyframe staggers are used together FAILED
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:938:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:938:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:938:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected [[object HTMLDivElement]] to have class 'ng-enter-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:938:25)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active should avoid applying the same cache to an element a follow-up animation is run on the same element FAILED
  Expected 'transition: all 0,5s linear; background: red;' not to contain 'transition'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:1597:41)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
  Expected 'transition-duration: 0,8s; transition-timing-function: linear; transition-property: all; background: blue;' not to contain 'transition'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:1607:41)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active structural animations should place a CSS transition block after the preparation function to block accidental style changes FAILED
  Expected '-5s' to match '-1.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:1764:51)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
      at window.inject.angular.mock.inject (angular.js/src/ngMock/angular-mocks.js:3037:42)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active structural animations should place a CSS transition block after the preparation function to block accidental style changes FAILED
  Expected '-5s' to match '-1.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:1764:51)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
      at window.inject.angular.mock.inject (angular.js/src/ngMock/angular-mocks.js:3037:42)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active structural animations should place a CSS transition block after the preparation function to block accidental style changes FAILED
  Expected '-5s' to match '-1.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:1764:51)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
      at window.inject.angular.mock.inject (angular.js/src/ngMock/angular-mocks.js:3037:42)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active structural animations should place a CSS transition block after the preparation function to block accidental style changes FAILED
  Expected '-5s' to match '-1.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:1764:51)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
      at window.inject.angular.mock.inject (angular.js/src/ngMock/angular-mocks.js:3037:42)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active structural animations should place a CSS transition block after the preparation function to block accidental style changes FAILED
  Expected '-5s' to match '-1.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:1764:51)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
      at window.inject.angular.mock.inject (angular.js/src/ngMock/angular-mocks.js:3037:42)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active options [duration] should remove all inline keyframe delay styling when an animation completes if a custom duration was applied FAILED
  Expected 'animation-delay: 5s;' to be falsy.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:2207:41)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active options [keyframeStyle] should apply the keyframe animation directly onto the element and animate accordingly FAILED
  Expected 'animation: my_animation 5,5s;' to contain '5.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:2657:33)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active options [keyframeStyle] should give priority to the provided delay value, but only update the duration style itself FAILED
  Expected '5,5s' to equal '5.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:2710:80)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active options [keyframeStyle] should be able to execute the animation if it is the only provided value FAILED
  Expected '5,5s' to equal '5.5s'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:2727:80)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active options [from] and [to] should remove all inline transition styling when an animation completes FAILED
  Expected 'transition: all 2,5s linear; background: red;' not to contain 'transition'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:2873:29)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active options [from] and [to] should retain existing styles when an inline styled animation completes FAILED
  Expected '0,5' to equal '0.5'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:2898:42)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4) ngAnimate $animateCss when active options should round up long elapsedTime values to close off a CSS3 animation FAILED
  Expected [[object HTMLDivElement]] not to have class 'ng-leave-active'.
      at Object.<anonymous> (angular.js/test/ngAnimate/animateCssSpec.js:3158:29)
      at Object.invoke (angular.js/src/auto/injector.js:867:19)
      at Object.workFn (angular.js/src/ngMock/angular-mocks.js:3068:20)
Chrome 50.0.2661 (Mac OS X 10.11.4): Executed 5216 of 5216 (16 FAILED) (17.666 secs / 17.011 secs)
```

**Comment by Narretz** [comment]
Works for me on Win7, Chrome 50.0.2661 and German locale. Strange.

**Comment by gkalpak** [comment]
It works for me on Win 10, Chrome 50 and Greek locale (where `,` is the decimal separator as well). Strange...

**Comment by mprobst** [comment]
I'm running on Mac OS. Maybe the issue is that on Linux, sub processes
inherit the LOCALE environment? The test is clearly wrong - it should not
compare the toString of a double.

**Comment by mprobst** [comment]
Talked to folks, this appears to be a Chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=609221
