### ISSUE TITLE
(bug) ngAnimate element.parent is not a function for empty jqLite collection

### ISSUE THREAD

**Issue by maksimr** [angular/angular.js#14558]
angular@1.5.5
angular-animate@1.5.5
angular-gettext@2.2.1

Use case which reproduce the problem:

http://jsbin.com/zaviju/edit?html,js,output

```html
<!DOCTYPE html>
<html>
<head>
<meta name="description" content="[add your bin description]">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>

<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular-animate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-gettext/2.2.1/angular-gettext.js"></script>
</head>



<body ng-app="app">

<span translate="">
</span>

<script>
   angular.module('app', ['ngAnimate','gettext']);
</script>
</body>
</html>
```

ER: No javascript exception
AR: 
```
runner-3.35.12.min.js:1 TypeError: element.parent is not a function
    at queueAnimation (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular-animate.js:2461:26)
    at Object.$animate.push (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular-animate.js:2411:16)
    at Object.enter (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:5398:31)
    at update (https://cdnjs.cloudflare.com/ajax/libs/angular-gettext/2.2.1/angular-gettext.js:447:34)
    at post (https://cdnjs.cloudflare.com/ajax/libs/angular-gettext/2.2.1/angular-gettext.js:463:21)
    at invokeLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:9694:9)
    at nodeLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:9093:11)
    at compositeLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:8397:13)
    at compositeLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:8400:13)
    at publicLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:8277:30) <span translate="">
```

Related issues:
https://github.com/angular/angular.js/issues/11703
https://github.com/rubenv/angular-gettext/issues/255

**Comment by gkalpak** [comment]
I am pretty sure this has been reported before, but I can't find the issue.
:+1:

**Comment by maksimr** [comment]
@gkalpak I have added related issues to my description :)  
Issue https://github.com/angular/angular.js/issues/11703 has same error message but another reason

Thanks

**Comment by maksimr** [comment]
@gkalpak when can we expect new version in npm?

**Comment by gkalpak** [comment]
> I am pretty sure this has been reported before, but I can't find the issue.

That's what I had in mind: https://github.com/angular/angular.js/commit/2aacc2d622893e05eb94b3974d562e681cc3a17f#commitcomment-17251606

> when can we expect new version in npm?

Hopefully before the end of next week :smiley:

<sub>BTW, I hadn't preperly backported it to `v1.5.x`. Fixing it now...</sub>
