### ISSUE TITLE
ENORESTARGET Tag/branch >=1.3.x && <= 1.5.x does not exist

### ISSUE THREAD

**Issue by jaitor1** [angular/angular.js#14930]
I don't know exactly if this is the place to post this issue:

My project has been working perfectly until yesterday.
I just did "bower install" and now I am getting the following error:

```
> bower install
bower slimScroll#~1.3.6         cached https://github.com/rochal/jQuery-slimScroll.git#1.3.8
bower slimScroll#~1.3.6       validate 1.3.8 against https://github.com/rochal/jQuery-slimScroll.git#~1.3.6
bower PACE#~1.0.2               cached https://github.com/HubSpot/pace.git#1.0.2
bower PACE#~1.0.2             validate 1.0.2 against https://github.com/HubSpot/pace.git#~1.0.2
bower angular-animate#*         cached https://github.com/angular/bower-angular-animate.git#1.5.7
bower angular-animate#*       validate 1.5.7 against https://github.com/angular/bower-angular-animate.git#*
bower jquery#~2.1.1             cached https://github.com/jquery/jquery-dist.git#2.1.4
bower jquery#~2.1.1           validate 2.1.4 against https://github.com/jquery/jquery-dist.git#~2.1.1
bower angular#1.5.7             cached https://github.com/angular/bower-angular.git#1.5.7
bower angular#1.5.7           validate 1.5.7 against https://github.com/angular/bower-angular.git#1.5.7
bower angular-resource#*        cached https://github.com/angular/bower-angular-resource.git#1.5.7
bower angular-resource#*      validate 1.5.7 against https://github.com/angular/bower-angular-resource.git#*
bower angular-route#*           cached https://github.com/angular/bower-angular-route.git#1.5.7
bower angular-route#*         validate 1.5.7 against https://github.com/angular/bower-angular-route.git#*
bower angular-sanitize#*        cached https://github.com/angular/bower-angular-sanitize.git#1.5.7
bower angular-sanitize#*      validate 1.5.7 against https://github.com/angular/bower-angular-sanitize.git#*
bower angular-toastr#*          cached https://github.com/Foxandxss/angular-toastr.git#1.7.0
bower angular-toastr#*        validate 1.7.0 against https://github.com/Foxandxss/angular-toastr.git#*
bower angular-translate#*       cached https://github.com/PascalPrecht/bower-angular-translate.git#2.11.1
bower angular-translate#*     validate 2.11.1 against https://github.com/PascalPrecht/bower-angular-translate.git#*
bower angular-datatables#*      cached https://github.com/l-lin/angular-datatables.git#0.5.4
bower angular-datatables#*    validate 0.5.4 against https://github.com/l-lin/angular-datatables.git#*
bower angular-ui-router#*       cached https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-ui-router#*     validate 0.3.1 against https://github.com/angular-ui/angular-ui-router-bower.git#*
bower bootstrap#~3.3.6          cached https://github.com/twbs/bootstrap.git#3.3.6
bower bootstrap#~3.3.6        validate 3.3.6 against https://github.com/twbs/bootstrap.git#~3.3.6
bower jquery-ui#~1.11.1         cached https://github.com/components/jqueryui.git#1.11.4
bower jquery-ui#~1.11.1       validate 1.11.4 against https://github.com/components/jqueryui.git#~1.11.1
bower angular-bootstrap#~0.12.0 cached https://github.com/angular-ui/bootstrap-bower.git#0.12.1
bower angular-bootstrap#~0.12.0         validate 0.12.1 against https://github.com/angular-ui/bootstrap-bower.git#~0.12.0
bower fontawesome#~4.3.0                  cached https://github.com/FortAwesome/Font-Awesome.git#4.3.0
bower fontawesome#~4.3.0                validate 4.3.0 against https://github.com/FortAwesome/Font-Awesome.git#~4.3.0
bower oclazyload#*                        cached https://github.com/ocombe/ocLazyLoad.git#1.0.9
bower oclazyload#*                      validate 1.0.9 against https://github.com/ocombe/ocLazyLoad.git#*
bower angular-messages#*                  cached https://github.com/angular/bower-angular-messages.git#1.5.7
bower angular-messages#*                validate 1.5.7 against https://github.com/angular/bower-angular-messages.git#*
bower ng-idle#*                           cached https://github.com/HackedByChinese/ng-idle.git#1.2.2
bower ng-idle#*                         validate 1.2.2 against https://github.com/HackedByChinese/ng-idle.git#*
bower metisMenu#~2.0.2                    cached https://github.com/onokumus/metisMenu.git#2.0.3
bower metisMenu#~2.0.2                  validate 2.0.3 against https://github.com/onokumus/metisMenu.git#~2.0.2
bower requirejs#2.1.10                    cached https://github.com/jrburke/requirejs-bower.git#2.1.10
bower requirejs#2.1.10                  validate 2.1.10 against https://github.com/jrburke/requirejs-bower.git#2.1.10
bower qunit#1.14.0                        cached https://github.com/jquery/qunit.git#1.14.0
bower qunit#1.14.0                      validate 1.14.0 against https://github.com/jquery/qunit.git#1.14.0
bower sizzle#2.1.1-jquery.2.1.2           cached https://github.com/jquery/sizzle.git#2.1.1-jquery.2.1.2
bower sizzle#2.1.1-jquery.2.1.2         validate 2.1.1-jquery.2.1.2 against https://github.com/jquery/sizzle.git#2.1.1-jquery.2.1.2
bower sinon#1.8.1                         cached https://github.com/cjohansen/Sinon.JS.git#1.8.1
bower sinon#1.8.1                       validate 1.8.1 against https://github.com/cjohansen/Sinon.JS.git#1.8.1
bower sweetalert#*                        cached https://github.com/t4t5/sweetalert.git#1.1.3
bower sweetalert#*                      validate 1.1.3 against https://github.com/t4t5/sweetalert.git#*
bower angular-ui-tree#~2.15.0             cached https://github.com/JimLiu/angular-ui-tree.git#2.15.0
bower angular-ui-tree#~2.15.0           validate 2.15.0 against https://github.com/JimLiu/angular-ui-tree.git#~2.15.0
bower angular-datepicker#~2.0.3           cached https://github.com/g00fy-/angular-datepicker.git#2.0.3
bower angular-datepicker#~2.0.3         validate 2.0.3 against https://github.com/g00fy-/angular-datepicker.git#~2.0.3
bower satellizer#*                        cached https://github.com/sahat/satellizer.git#0.15.0
bower satellizer#*                      validate 0.15.0 against https://github.com/sahat/satellizer.git#*
bower angular-highlightjs#~0.5.1          cached https://github.com/pc035860/angular-highlightjs.git#0.5.1
bower angular-highlightjs#~0.5.1        validate 0.5.1 against https://github.com/pc035860/angular-highlightjs.git#~0.5.1
bower angular-csv-import#~0.0.29          cached https://github.com/bahaaldine/angular-csv-import.git#0.0.36
bower angular-csv-import#~0.0.29        validate 0.0.36 against https://github.com/bahaaldine/angular-csv-import.git#~0.0.29
bower angular-mocks#*                     cached https://github.com/angular/bower-angular-mocks.git#1.5.7
bower angular-mocks#*                   validate 1.5.7 against https://github.com/angular/bower-angular-mocks.git#*
bower angular-touch#*                     cached https://github.com/angular/bower-angular-touch.git#1.5.7
bower angular-touch#*                   validate 1.5.7 against https://github.com/angular/bower-angular-touch.git#*
bower datatables#>=1.10.9                 cached https://github.com/DataTables/DataTables.git#1.10.12
bower datatables#>=1.10.9               validate 1.10.12 against https://github.com/DataTables/DataTables.git#>=1.10.9
bower angular#>=1 <1.3.0                  cached https://github.com/angular/bower-angular.git#1.2.29
bower angular#>=1 <1.3.0                validate 1.2.29 against https://github.com/angular/bower-angular.git#>=1 <1.3.0
bower angular#1.2.14                      cached https://github.com/angular/bower-angular.git#1.2.14
bower angular#1.2.14                    validate 1.2.14 against https://github.com/angular/bower-angular.git#1.2.14
bower moment#~2.10.6                      cached https://github.com/moment/moment.git#2.10.6
bower moment#~2.10.6                    validate 2.10.6 against https://github.com/moment/moment.git#~2.10.6
bower moment-timezone#~0.4.1              cached https://github.com/moment/moment-timezone.git#0.4.1
bower moment-timezone#~0.4.1            validate 0.4.1 against https://github.com/moment/moment-timezone.git#~0.4.1
bower angular#>=1.3.x && <= 1.5.x     not-cached https://github.com/angular/bower-angular.git#>=1.3.x && <= 1.5.x
bower angular#>=1.3.x && <= 1.5.x        resolve https://github.com/angular/bower-angular.git#>=1.3.x && <= 1.5.x
bower angular#>=1.3.x && <= 1.5.x   ENORESTARGET Tag/branch >=1.3.x && <= 1.5.x does not exist




Additional error details:
Available tags: v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.2.0, v1.2.0-rc.1, v1.2.0-rc.2, v1.2.0-rc.3, v1.2.1, v1.2.10, v1.2.10-build.2136+sha.8ea8da4, v1.2.10-build.2139+sha.61eb426, v1.2.10-build.2140+sha.51a7f9d, v1.2.10-build.2141+sha.cd0af8a, v1.2.10-build.2142+sha.e591ddc, v1.2.10-build.2143+sha.6a9ccac, v1.2.10-build.2144+sha.6a9ccac, v1.2.10-build.2145+sha.6a9ccac, v1.2.10-build.2146+sha.0e4d7ca, v1.2.10-build.2147+sha.1cdcddb, v1.2.10-build.2148+sha.fced1c0, v1.2.10-build.2149+sha.cd74f74, v1.2.10-build.2150+sha.2262ca6, v1.2.10-build.2151+sha.5adea0b, v1.2.10-build.2152+sha.7ba30fd, v1.2.10-build.2153+sha.8dd4f14, v1.2.10-build.2154+sha.c3e1a41, v1.2.10-build.2155+sha.756c52d, v1.2.10-build.2156+sha.1028cfa, v1.2.10-build.2157+sha.42ec95e, v1.2.10-build.2158+sha.42ec95e, v1.2.10-build.2159+sha.190c4f9, v1.2.10-build.2160+sha.928d000, v1.2.10-build.2161+sha.90e60d2, v1.2.10-build.2162+sha.99c5027, v1.2.10-build.2163+sha.6c9131e, v1.2.10-build.2164+sha.8b395ff, v1.2.10-build.2165+sha.2068d76, v1.2.10-build.2166+sha.5b9ff6c, v1.2.10-build.2167+sha.6d525f0, v1.2.10-build.2168+sha.310f129, v1.2.10-build.2169+sha.7cf5544, v1.2.10-build.2170+sha.7cf5544, v1.2.10-build.2171+sha.79e519f, v1.2.10-build.2172+sha.ec59be6, v1.2.10-build.2173+sha.82213ef, v1.2.10-build.2174+sha.486bdf2, v1.2.10-build.2175+sha.c3b5e16, v1.2.10-build.2176+sha.e020916, v1.2.10-build.2177+sha.5e9835b, v1.2.10-build.2178+sha.40dc806, v1.2.10-build.2179+sha.ca6b7d0, v1.2.10-build.2180+sha.131410b, v1.2.10-build.2181+sha.4f827f5, v1.2.11, v1.2.11-build.2182+sha.88a14b4,
...
[It continues like that for preety long]
....
 v1.5.8-build.4932+sha.c253b8e, v1.5.8-build.4934+sha.489224b, v1.5.8-build.4935+sha.859b1e3, v1.5.8-build.4940+sha.c8a6481, v1.5.8-build.4941+sha.aea62af, v1.5.8-build.4942+sha.cd06ccc, v1.5.8-build.4943+sha.26dac57, v1.5.8-build.4944+sha.56d4563, v1.5.8-build.4945+sha.47583d9, v1.5.8-build.4946+sha.c13c666
Available branches: master, unstable
```

My bower.json:

```
{
  "name": "myapp",
  "version": "1.0.0",
  "dependencies": {
        "jquery": "~2.1.1",
        "angular": "1.5.7",
        "angular-animate": "latest",
        "angular-datatables": "latest",
        "angular-messages": "latest",
        "angular-mocks": "latest",
        "angular-resource": "latest",
        "angular-route": "latest",
        "angular-sanitize": "latest",
        "angular-toastr": "latest",
        "angular-touch": "latest",
        "angular-translate": "latest",
        "angular-ui-router": "latest",
        "bootstrap": "~3.3.6",
        "jquery-ui": "~1.11.1",
        "angular-bootstrap": "~0.12.0",
        "ng-idle":"latest",
        "oclazyload": "latest",
        "metisMenu": "~2.0.2",
        "fontawesome": "~4.3.0",
        "slimScroll": "https://github.com/rochal/jQuery-slimScroll.git#~1.3.6",
        "PACE": "https://github.com/HubSpot/pace.git#~1.0.2",
        "sizzle": "2.1.1-jquery.2.1.2",
        "requirejs": "2.1.10",
        "qunit": "1.14.0",
        "sinon": "1.8.1",
        "satellizer": "latest",
        "sweetalert": "latest",
        "angular-ui-tree": "~2.15.0",
      "angular-csv-import": "~0.0.29",
      "angular-highlightjs":"~0.5.1",
      "angular-datepicker":"~2.0.3"
      
  },
  "authors": [
    "jaitor1"
  ],
  "description": "myapp",
  "main": "public/index.html",
  "moduleType": [
    "globals"
  ],
  "keywords": [
    "angular"
  ],
  "homepage": "",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "public/libs",
    "test",
    "tests"
  ],
    "resolutions": {
      "angular": "1.5.7"
    }
}

```

bower install -V print aditional info:

```
Stack trace:
Error: Tag/branch >=1.3.x && <= 1.5.x does not exist
    at createError (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitResolver.js:183:15
From previous event:
    at GitHubResolver.GitResolver._findResolution (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitResolver.js:159:6)
    at GitHubResolver.GitRemoteResolver._findResolution (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitRemoteResolver.js:98:50)
    at GitHubResolver.GitResolver._resolve (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitResolver.js:67:17)

Console trace:
Error
    at StandardRenderer.error (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\jaitor\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 4.2.2
OS: Windows_NT 6.3.9600 x64
```

How could I solve this??

**Comment by gkalpak** [comment]
I don't think that `>=1.3.x && <= 1.5.x` is an allowed version range format (according to the [current docs][1]). It should probably be `>=1.3.x <= 1.5.x`. 

You need to find out where that comes from (e.g. it could be a dependency of one of your dependencies). Maybe you updated some dependency, which brings along that invalid version range.

--
<sub>Closing since this is not related to Angular itself.</sub>

[1]: https://bower.io/docs/api/#install

**Comment by jaitor1** [comment]
@gkalpak I did not update any dependencies for several weeks, and it has been working perfectly until yesterday. I just pasted an replace some project files (with updates), but it has nothing to do with bower... I am pretty stuck and I am quite new to bower and git and I am not capable of going deeper in the issue, any advice?

**Comment by jaitor1** [comment]
angular-datatables says in [his bower.json](https://github.com/l-lin/angular-datatables/blob/dev/bower.json) that:

  "dependencies": {
         "angular": ">=1.3.0"
   }

Could be due to this?

**Comment by gkalpak** [comment]
I doubt it. I suspect some dependency (or subdependency) incorrectly declares `>=1.3.x && <=1.5.x` as the required version. I would try asking on one of the [general support channels][1].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
