### ISSUE TITLE
Error when opens the localhost in chromium

### ISSUE THREAD

**Issue by exp-christy** [angular/angular.js#15609]
angular.js:14328 TypeError: undefined is not a function
    at Array.filter (native)
    at fn (eval at compile (http://localhost:3000/bower_components/angular/angular.js:15156:15), <anonymous>:4:379)
    at regularInterceptedExpression (http://localhost:3000/bower_components/angular/angular.js:16264:55)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:17806:34)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:18080:24)
    at done (http://localhost:3000/bower_components/angular/angular.js:12210:47)
    at completeRequest (http://localhost:3000/bower_components/angular/angular.js:12436:7)
    at XMLHttpRequest.requestLoaded (http://localhost:3000/bower_components/angular/angular.js:12364:9)(anonymous function) @ angular.js:14328(anonymous function) @ angular.js:10837$digest @ angular.js:17832$apply @ angular.js:18080done @ angular.js:12210completeRequest @ angular.js:12436requestLoaded @ angular.js:1236

How to solve this issue

**Comment by frederikprijck** [comment]
@exp-christy Do you have some code or a plunkr example perhaps?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions (providing more info and/or a reproduction, as suggested by @frederikprijck).
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
