### ISSUE TITLE
Lazy transclusion exception in angular 1.6.1

### ISSUE THREAD

**Issue by DineshkumarT** [angular/angular.js#15667]
After upgrading to angular 1.6.1, I am facing the following exception 

 at Object.invoke (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:4842:19)
    at $controllerInit (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:10695:34)
    at nodeLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:9572:35)
    at compositeLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:8881:13)
    at compositeLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:8884:13)
    at publicLinkFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:8746:30)
    at lazyCompilation (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:9137:25)
    at boundTranscludeFn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:8924:16)
    at Object.controllersBoundTransclude [as transclude] (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js:9691:20)undefined

Please let me know how to resolve this issue

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

also, amke sure you have read through the [Migration Guide][2], which has more details about all breaking changes.  

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://code.angularjs.org/snapshot/docs/guide/migration#migrating-from-1-5-to-1-6
