### ISSUE TITLE
angular.min.js:118 SyntaxError: Illegal continue statement

### ISSUE THREAD

**Issue by tousif12** [angular/angular.js#16041]
I run a old application build in 2015. Now by using Node.js and running server all things are good but angular js is not running.  can Anybody tell me what is error ?  As I didnt found any help on internet. 

```
angular.min.js:118 SyntaxError: Illegal continue statement
    at Object.instantiate (http://localhost:3000/lib/js/angular.min.js:42:56)
    at http://localhost:3000/lib/js/angular.min.js:90:32
    at Object.link (http://localhost:3000/lib/js/angular-route.min.js:7:274)
    at http://localhost:3000/lib/js/angular.min.js:16:71
    at la (http://localhost:3000/lib/js/angular.min.js:81:90)
    at p (http://localhost:3000/lib/js/angular.min.js:66:341)
    at g (http://localhost:3000/lib/js/angular.min.js:58:481)
    at http://localhost:3000/lib/js/angular.min.js:58:119
    at http://localhost:3000/lib/js/angular.min.js:63:39
    at d (http://localhost:3000/lib/js/angular.min.js:59:474) <div ng-view="" class="ng-scope" data-ng-animate="1">
```

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
