### ISSUE TITLE
Transpiled classes do not work with #service and #config

### ISSUE THREAD

**Issue by VoidOutput** [angular/angular.js#16545]
Hello, please forgive me if this issue is not relevant: I'm not sure that this issue is a problem in Angular.js but I'm not sure that this isn't a problem in Babel either, so here goes.

**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Transpiling ES6 classes with Babel and using them with #config() or #service() seems to fail because Babel transpiles it into a regular function that happens to have a check in its "constructor" that prevents it from being called without a new (I imagine this is to reproduce the behavior in other browsers). However I think this is a bug in Angular.js because such classes can be provided to controllers and components with no error thrown.

Maybe this is the isClass method that is at fault? https://github.com/angular/angular.js/blob/a7e5e83240f9539ffa0d4b429d30440c11775e76/src/auto/injector.js#L917

I tried to add static $$ngIsClass properties to each class, but then this didn't work in IE so I don't think this is a reasonable solution either.

**Minimal reproduction of the problem with instructions:**

Here's a plunker where I managed to reproduce the error: http://plnkr.co/edit/v1fge8Z0OxvzLnaUn9fI?preview&p=preview

**AngularJS version:** 1.6.10

**Browser:** all

**Anything else:**

Here's a stacktrace of the error from Plunker:

```
angular.js:125 Uncaught Error: [$injector:modulerr] Failed to instantiate module plunker due to:
TypeError: Cannot call a class as a function
    at _classCallCheck (http://run.plnkr.co/9rvKsi0uip4ScdPi/app.js:32:99)
    at CompileConfig (http://run.plnkr.co/9rvKsi0uip4ScdPi/app.js:38:5)
    at Object.invoke (https://code.angularjs.org/1.6.10/angular.js:5117:19)
    at runInvokeQueue (https://code.angularjs.org/1.6.10/angular.js:5004:35)
    at https://code.angularjs.org/1.6.10/angular.js:5014:11
    at forEach (https://code.angularjs.org/1.6.10/angular.js:418:20)
    at loadModules (https://code.angularjs.org/1.6.10/angular.js:4994:5)
    at createInjector (https://code.angularjs.org/1.6.10/angular.js:4911:19)
    at doBootstrap (https://code.angularjs.org/1.6.10/angular.js:1965:20)
    at bootstrap (https://code.angularjs.org/1.6.10/angular.js:1986:12)
https://errors.angularjs.org/1.6.10/$injector/modulerr?p0=plunker&p1=TypeError%3A%20Cannot%20call%20a%20class%20as%20a%20function%0A%20%20%20%20at%20_classCallCheck%20(http%3A%2F%2Frun.plnkr.co%2F9rvKsi0uip4ScdPi%2Fapp.js%3A32%3A99)%0A%20%20%20%20at%20CompileConfig%20(http%3A%2F%2Frun.plnkr.co%2F9rvKsi0uip4ScdPi%2Fapp.js%3A38%3A5)%0A%20%20%20%20at%20Object.invoke%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A5117%3A19)%0A%20%20%20%20at%20runInvokeQueue%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A5004%3A35)%0A%20%20%20%20at%20https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A5014%3A11%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A418%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A4994%3A5)%0A%20%20%20%20at%20createInjector%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A4911%3A19)%0A%20%20%20%20at%20doBootstrap%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A1965%3A20)%0A%20%20%20%20at%20bootstrap%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A1986%3A12)
    at _classCallCheck (http://run.plnkr.co/9rvKsi0uip4ScdPi/app.js:32:99)
    at CompileConfig (http://run.plnkr.co/9rvKsi0uip4ScdPi/app.js:38:5)
    at Object.invoke (https://code.angularjs.org/1.6.10/angular.js:5117:19)
    at runInvokeQueue (https://code.angularjs.org/1.6.10/angular.js:5004:35)
    at https://code.angularjs.org/1.6.10/angular.js:5014:11
    at forEach (https://code.angularjs.org/1.6.10/angular.js:418:20)
    at loadModules (https://code.angularjs.org/1.6.10/angular.js:4994:5)
    at createInjector (https://code.angularjs.org/1.6.10/angular.js:4911:19)
    at doBootstrap (https://code.angularjs.org/1.6.10/angular.js:1965:20)
    at bootstrap (https://code.angularjs.org/1.6.10/angular.js:1986:12)
https://errors.angularjs.org/1.6.10/$injector/modulerr?p0=plunker&p1=TypeError%3A%20Cannot%20call%20a%20class%20as%20a%20function%0A%20%20%20%20at%20_classCallCheck%20(http%3A%2F%2Frun.plnkr.co%2F9rvKsi0uip4ScdPi%2Fapp.js%3A32%3A99)%0A%20%20%20%20at%20CompileConfig%20(http%3A%2F%2Frun.plnkr.co%2F9rvKsi0uip4ScdPi%2Fapp.js%3A38%3A5)%0A%20%20%20%20at%20Object.invoke%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A5117%3A19)%0A%20%20%20%20at%20runInvokeQueue%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A5004%3A35)%0A%20%20%20%20at%20https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A5014%3A11%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A418%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A4994%3A5)%0A%20%20%20%20at%20createInjector%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A4911%3A19)%0A%20%20%20%20at%20doBootstrap%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A1965%3A20)%0A%20%20%20%20at%20bootstrap%20(https%3A%2F%2Fcode.angularjs.org%2F1.6.10%2Fangular.js%3A1986%3A12)
    at https://code.angularjs.org/1.6.10/angular.js:125:12
    at https://code.angularjs.org/1.6.10/angular.js:5034:15
    at forEach (https://code.angularjs.org/1.6.10/angular.js:418:20)
    at loadModules (https://code.angularjs.org/1.6.10/angular.js:4994:5)
    at createInjector (https://code.angularjs.org/1.6.10/angular.js:4911:19)
    at doBootstrap (https://code.angularjs.org/1.6.10/angular.js:1965:20)
    at bootstrap (https://code.angularjs.org/1.6.10/angular.js:1986:12)
    at angularInit (https://code.angularjs.org/1.6.10/angular.js:1871:5)
    at https://code.angularjs.org/1.6.10/angular.js:34875:5
    at HTMLDocument.trigger (https://code.angularjs.org/1.6.10/angular.js:3499:5)
```

Please tell me if there is anything I can add to this report, or if I did anything wrong, this is my first one. I'm open to the possibility that this is actually expected behavior or that resources are low to fix this. I'm also open to making a merge request if I'm pointed to the appropriate code to change.

**Comment by frederikprijck** [comment]
Hey,
This should work fine for services, as AngularJS expects a constructor function as second argument when calling `service()`.

When using `config()`, classes won't work. This isn't a bug but expected behavior. Not everything has to be classes, for config you only need a function as it's only a single execution of a specific code-block, which is totally different from controllers and services (which allow the usage of classes).

**Comment by VoidOutput** [comment]
I appreciate your quick comments, it was a misunderstanding of these methods' arguments on my part. I can confirm that everything works correctly with your suggestions.

Thank you both for your time and patience!
