### ISSUE TITLE
intermitten bug: cannot read property '$$phase' of null

### ISSUE THREAD

**Issue by stripathix** [angular/angular.js#16583]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

 It is a intermitten problem can't reporduce but It happend when I was switch state from dashbord to account

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.10

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

TypeError: Cannot read property '$$phase' of null
  at $$debounceViewValueCommit(../app/node_modules/angular/angular.min.js:301:520)
  at $setViewValue(../app/node_modules/angular/angular.min.js:301:207)
  at call(../app/node_modules/angular/angular.min.js:184:85)
  at lg(../app/node_modules/angular/angular.min.js:40:48)
  at apply(../app/node_modules/angular/angular.min.js:39:497)
  at HTMLInputElement.d(../app/node_modules/raven-js/dist/raven.min.js:2:4706)

**Comment by gkalpak** [comment]
It is hard to investigate without a reproduction 😞
Do you at least know which browsers are affected. (Could it be that this only happens on IE?)

- The error seems to happen on [this line][1], when `$$scope.$root` is null.
- This happens when `$$scope` has been [destroyed][2].
- AFAICT, for the error to appear, `$setViewValue()` has to be called asynchronously and scope be destroyed between scheduling `$setViewValue()` and actually invoking it.
- This can (only?) happen if the [input listener][3] is [called asynchronously][4], which happens on browsers that do not support the `input` event (i.e. IE).

##
It sounds reasonable to add a check for `$$scope.$$destroyed` in `$setViewValue()` or `$$debounceViewValueCommit()`. But without a way to reproduce the issue, we can't be sure if it is actually fixing anything :grin:

[1]: https://github.com/angular/angular.js/blob/78b9f61366faa1fd4460412771a65f8f01406ed0/src/ng/directive/ngModel.js#L867
[2]: https://github.com/angular/angular.js/blob/78b9f61366faa1fd4460412771a65f8f01406ed0/src/ng/rootScope.js#L131-L132
[3]: https://github.com/angular/angular.js/blob/78b9f61366faa1fd4460412771a65f8f01406ed0/src/ng/directive/input.js#L1311-L1333
[4]: https://github.com/angular/angular.js/blob/78b9f61366faa1fd4460412771a65f8f01406ed0/src/ng/directive/input.js#L1340-L1349

**Comment by gkalpak** [comment]
@stripathix, if you feel like taking a stab at it, feel free to submit a pull request :grin:
<sub>(Also feel free to ping me if you need any help/guidance/info.)</sub>

**Comment by stripathix** [comment]
Below is the environment information:
Chrome Version: 66.0.3359
Windows 10
