### ISSUE TITLE
self.url Method causes trouble with IE11 (routing)

### ISSUE THREAD

**Issue by PatrikFrie** [angular/angular.js#16825]
**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Our angularjs app is using the adal-angular library for Azure-AD authentication in an MS Dynamics environment. Since two years now, we don't have had any issues with that. 

**Overnight**, all of our clients became trouble with the authentication but **only** in the Dynamics CRM Add-In for **Outlook**. With that Add-In, you can use the Dynamics web-interface just integrated in Outlook.
Actually, Outlook is using the same Internet Explorer instance and version as the default Windows version. 
That issue only appears in the Internet Explorer 11 version used by Outlook. And happened overnight.
The default IE 11 instance of Windows is still working fine. 

Console and debugging output:

Unknown error:
at self.url (**/libs/vanillaJS_libs_bundle.js:6545:13)
at Anonymous function (**/vanillaJS_libs_bundle.js:14559:21)
at invoke (**/vanillaJS_libs_bundle.js:5117:21)
at Anonymous function (**/vanillaJS_libs_bundle.js:4904:21)
at getService (**/vanillaJS_libs_bundle.js:5058:25)
at injectionArgs (**/vanillaJS_libs_bundle.js:5082:21)
at instantiate (**/vanillaJS_libs_bundle.js:5129:17)
at $controller (**/vanillaJS_libs_bundle.js:11106:17)
at Anonymous function (**/ng_modules_bundle.js:630:9122)
at processQueue (**/vanillaJS_libs_bundle.js:17170:29) Possibly unhandled rejection: {"description":"Unbekannter Fehler.","number":-2147467259,"stack":"Error: Unknown Issue.\n   
at self.url (**/vanillaJS_libs_bundle.js:6545:13)\n   at Anonymous function (**/vanillaJS_libs_bundle.js:14559:21)\n   at invoke (**/vanillaJS_libs_bundle.js:5117:21)\n   at Anonymous function (**/vanillaJS_libs_bundle.js:4904:21)\n   at getService (**/vanillaJS_libs_bundle.js:5058:25)\n   at injectionArgs (**/vanillaJS_libs_bundle.js:5082:21)\n   at instantiate (**/vanillaJS_libs_bundle.js:5129:17)\n   at $controller (**/vanillaJS_libs_bundle.js:11106:17)\n   at Anonymous function (**/angular/modules/ng_modules_bundle.js:630:9122)\n   at processQueue (**/vanillaJS_libs_bundle.js:17170:29)"}

That error appears in the angularjs lib in the function
**self.url = function(url, replace, state) {**
at line
**history[replace ? 'replaceState' : 'pushState'](state, '', url);**

Unfortunately, I can't debug deeper to get more details..
The url string is in any browser environment the same and replace is equal to true, before the error message appears. State is null.

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.7

**Browser:** [IE 11]

**Anything else:**

**Comment by petebacondarwin** [comment]
So the browser is not accepting a call to `window.history.replaceState(null, '', 'some/url');`. This is a very standard call which IE11 should support (see https://caniuse.com/#feat=history).

Given that nothing has changed on the AngularJS side, I would expect that the first port of call is to file an issue with the Add-in provider. Second you could also consider checking whether upgrading to the latest AngularJS 1.7.6 helps.

Otherwise I am not sure what else can be done.

**Comment by PatrikFrie** [comment]
I found out that it has anything to do with this snippet in my code:

`$locationProvider.html5Mode({
        enabled: true,
        requireBase: false
        }).hashPrefix('!');`

It's part of our own implementation. Since I haven't wrote that line in the past, do you have an idea why that could have any new negative effect?

**Comment by petebacondarwin** [comment]
Well first of all, enabling html5 mode should mean that hash prefix is irrelevant. Why did you set the require base to be false?

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Leave a comment if you can provide new feedback.
