### ISSUE TITLE
ngSanitize error lowercase is not a function

### ISSUE THREAD

**Issue by hitendrajagtap** [angular/angular.js#16918]
AngularJS v1.7.8, ngSanitize v1.7.8

can you provide a reproduction of your problem, and place it in a new issue?

_Originally posted by @petebacondarwin in https://github.com/angular/angular.js/issues/16567#issuecomment-493352376_

Error: [$injector:modulerr] Failed to instantiate module ngSanitize due to:
TypeError: lowercase is not a function
    at arrayToMap (http://localhost:4444/Scripts/angular-sanitize.js:417:27)
    at stringToMap (http://localhost:4444/Scripts/angular-sanitize.js:411:12)
    at $SanitizeProvider (http://localhost:4444/Scripts/angular-sanitize.js:389:18)

  function arrayToMap(items, lowercaseKeys) {
    var obj = {}, i;
    for (i = 0; i < items.length; i++) {
      obj[lowercaseKeys ? lowercase(items[i]) : items[i]] = true;
    }
    return obj;
  }

**Comment by hitendrajagtap** [comment]
Seems like lowercase is deprecated https://github.com/angular/angular.js/commit/1daa4f2231a89ee88345689f001805ffffa9e7de#diff-1d54c5f722aebc473dbe96f836ddf974
