### ISSUE TITLE
Error building docs

### ISSUE THREAD

**Issue by chanhoPark929** [angular/angular.js#17110]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.8.x

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]

**Anything else:**

I'm trying to build the document. 
I ran the following command
`npx grunt docs`

But I'm getting the error
`error:   Error processing docs:  Error: Cannot find module '../../../build/errors.json'
Require stack:
- C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\docs\config\processors\error-docs.js
- C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\docs\config\index.js
- C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\docs\gulpfile.js
- C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\node_modules\gulp\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.$process (C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\docs\config\processors\error-docs.js:15:29)
    at C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\node_modules\dgeni\lib\Dgeni.js:179:54
    at _fulfilled (C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\node_modules\dgeni\node_modules\q\q.js:834:54)
    at C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\node_modules\dgeni\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\node_modules\dgeni\node_modules\q\q.js:796:13)
    at C:\Users\Garibaldi\Downloads\angular.js-master\angular.js-master\node_modules\dgeni\node_modules\q\q.js:604:44`

**Comment by petebacondarwin** [comment]
This missing file is generated by the build. Please run `yarn grunt package` first to ensure that all the prerequisite files have been generated.
