### ISSUE TITLE
TypeError: Property 'scrollTo' of object [object global] is not a function

### ISSUE THREAD

**Issue by ocatteau** [angular/angular.js#2272]
It seems there is a problem on Chrome (tested on Mac and Windows - Version 26.0.1410.43 m). You can try on this page : http://docs.angularjs.org/tutorial
The backward functionnality also doesn't work anymore. It's certainly due to the same bug.

Here is the stacktrace picked from the console : 

TypeError: Property 'scrollTo' of object [object global] is not a function
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:30:3)
    at Object.e.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:87:347)
    at Object.e.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:85:198)
    at Object.e.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:87:506)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:16:21
    at Object.d [as invoke] (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:27:53)
    at qb (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:15:454)
    at jc (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:15:315)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:161:402
    at HTMLDocument.a (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.min.js:116:223) 

Thanks !

**Comment by Narretz** [comment]
As this happens only when 3rd party code breaks DOM apis, it doesn't make a lot of sense to fix this in angular. And the offending plugin doesn't seem to exist anymore, either.
