### ISSUE TITLE
Error: No controller: init

### ISSUE THREAD

**Issue by AidasK** [angular/angular.js#4232]
Directive require fails (with link) then including external template and using quick redirect.

Can't reproduce this in jsfiddle, because we need to load external template

Steps to reproduce this issue:
1. http://plnkr.co/edit/HPtMJhM30ezAxpClmgdT?p=preview
2. press "error" button
3. wholia

````
Error: No controller: init
    at Error (<anonymous>)
    at getControllers (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:4454:19)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:4583:35)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:4191:15)
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:4096:30)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:13588:43
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:9137:11
    at wrappedCallback (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:6995:59)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:7032:26
    at Object.Scope.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js:8218:28) <div init-require="" class="ng-scope ng-binding"> 
````

browsers: Chrome, IE10, maybe others too.

**Comment by Narretz** [comment]
Looks like this was recently fixed in 1.4.9 ;)
